### ISSUE TITLE
NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by YADeM** [centosadmin/redmine_intouch#1]
Переношу ошибку сюда
```
rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
```

полный лог
http://pastebin.com/vrygrSQ4

Я же правильно понял в сервисе redminebot я указываю APP_ROOT в ту папку, где у меня установлен редмайн?
Или пробую запускать через
bundle exec rake intouch:telegram:bot PID_DIR='/var/www/data/tmp/pids/telegram-bot.pid'

В redmine/config
я скопировал без изменения этот файл sidekiq.yml
Или в нем тоже нужно было указать абсолютные пути?
sidekiq и redis запущены, по крайней мере /sidekiq работает и показывает кол-во задач и обновляется иногда его лог файл — по другому как-то проверить можно?
Ранее была ошибка с htmlentities 4.3.1 — победил установкой дополнительно 4.3.4

**Comment by arturtr** [comment]
В `sidekiq.yml` можно относительные пути оставить.
Бот стартуется из корня редмайна.

По вашем логу видно что ошибка именно с sidekiq, поэтому вам нужно с ним разбираться. 

Ругается на эту строку
https://github.com/ogom/redmine_sidekiq/blob/master/lib/redmine_sidekiq/configure.rb#L8

Надо в конфиг редис прописать правильно. В общем это не в нашем плагине проблема, а том как вы настроили redmine_sidekiq и его окружение (redis)

**Comment by YADeM** [comment]
Спасибо, буду разбираться, а то для человека не знающего ruby тяжковато понять в чем накосячил
