### ISSUE TITLE
Краш

### ISSUE THREAD

**Issue by komato3huk** [centosadmin/redmine_intouch#10]
[2016-09-05T15:31:22.933461 #1723] ERROR -- : GLOBAL ERROR SystemExit: Aborted with HUP signal
/var/www/redmine/plugins/redmine_intouch/lib/tasks/intouch.rake:28:in `abort'
/var/www/redmine/plugins/redmine_intouch/lib/tasks/intouch.rake:28:in`block (4 levels) in <top (required)>'
/usr/lib/ruby/2.1.0/openssl/buffering.rb:61:in `call'
/usr/lib/ruby/2.1.0/openssl/buffering.rb:61:in`sysread'
/usr/lib/ruby/2.1.0/openssl/buffering.rb:61:in `fill_rbuff'
/usr/lib/ruby/2.1.0/openssl/buffering.rb:208:in`gets'
/var/lib/gems/2.1.0/gems/httpclient-2.8.2.2/lib/httpclient/ssl_socket.rb:74:in `gets'
/var/lib/gems/2.1.0/gems/httpclient-2.8.2.2/lib/httpclient/session.rb:799:in`block in parse_header'
/usr/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
/usr/lib/ruby/2.1.0/timeout.rb:101:in`call'
/usr/lib/ruby/2.1.0/timeout.rb:101:in `timeout'
/var/lib/gems/2.1.0/gems/httpclient-2.8.2.2/lib/httpclient/session.rb:795:in`parse_header'
/var/lib/gems/2.1.0/gems/httpclient-2.8.2.2/lib/httpclient/session.rb:778:in `read_header'
/var/lib/gems/2.1.0/gems/httpclient-2.8.2.2/lib/httpclient/session.rb:554:in`get_header'
/var/lib/gems/2.1.0/gems/httpclient-2.8.2.2/lib/httpclient.rb:1297:in `do_get_header'
/var/lib/gems/2.1.0/gems/httpclient-2.8.2.2/lib/httpclient.rb:1243:in`do_get_block'
/var/lib/gems/2.1.0/gems/httpclient-2.8.2.2/lib/httpclient.rb:1017:in `block in do_request'
/var/lib/gems/2.1.0/gems/httpclient-2.8.2.2/lib/httpclient.rb:1131:in`protect_keep_alive_disconnected'
/var/lib/gems/2.1.0/gems/httpclient-2.8.2.2/lib/httpclient.rb:1012:in `do_request'
/var/lib/gems/2.1.0/gems/httpclient-2.8.2.2/lib/httpclient.rb:854:in`request'
/var/lib/gems/2.1.0/gems/httpclient-2.8.2.2/lib/httpclient.rb:763:in `post'
/var/lib/gems/2.1.0/gems/telegrammer-0.8.0/lib/telegrammer/bot.rb:536:in`api_request'
/var/lib/gems/2.1.0/gems/telegrammer-0.8.0/lib/telegrammer/bot.rb:66:in `block in get_updates'
/var/lib/gems/2.1.0/gems/telegrammer-0.8.0/lib/telegrammer/bot.rb:61:in`loop'
/var/lib/gems/2.1.0/gems/telegrammer-0.8.0/lib/telegrammer/bot.rb:61:in `get_updates'
/var/www/redmine/plugins/redmine_intouch/lib/tasks/intouch.rake:58:in`block (3 levels) in <top (required)>'
/var/lib/gems/2.1.0/gems/rake-11.1.2/lib/rake/task.rb:248:in `call'
/var/lib/gems/2.1.0/gems/rake-11.1.2/lib/rake/task.rb:248:in`block in execute'
/var/lib/gems/2.1.0/gems/rake-11.1.2/lib/rake/task.rb:243:in `each'
/var/lib/gems/2.1.0/gems/rake-11.1.2/lib/rake/task.rb:243:in`execute'
/var/lib/gems/2.1.0/gems/rake-11.1.2/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.1.0/monitor.rb:211:in`mon_synchronize'
/var/lib/gems/2.1.0/gems/rake-11.1.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
/var/lib/gems/2.1.0/gems/rake-11.1.2/lib/rake/task.rb:173:in`invoke'
/var/lib/gems/2.1.0/gems/rake-11.1.2/lib/rake/application.rb:150:in `invoke_task'
/var/lib/gems/2.1.0/gems/rake-11.1.2/lib/rake/application.rb:106:in`block (2 levels) in top_level'
/var/lib/gems/2.1.0/gems/rake-11.1.2/lib/rake/application.rb:106:in `each'
/var/lib/gems/2.1.0/gems/rake-11.1.2/lib/rake/application.rb:106:in`block in top_level'
/var/lib/gems/2.1.0/gems/rake-11.1.2/lib/rake/application.rb:115:in `run_with_threads'
/var/lib/gems/2.1.0/gems/rake-11.1.2/lib/rake/application.rb:100:in`top_level'
/var/lib/gems/2.1.0/gems/rake-11.1.2/lib/rake/application.rb:78:in `block in run'
/var/lib/gems/2.1.0/gems/rake-11.1.2/lib/rake/application.rb:176:in`standard_exception_handling'
/var/lib/gems/2.1.0/gems/rake-11.1.2/lib/rake/application.rb:75:in `run'
/var/lib/gems/2.1.0/gems/rake-11.1.2/bin/rake:33:in`<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in`<top (required)>'
/var/lib/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/cli/exec.rb:63:in `load'
/var/lib/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/cli/exec.rb:63:in`kernel_load'
/var/lib/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/cli/exec.rb:24:in `run'
/var/lib/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/cli.rb:304:in`exec'
/var/lib/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in`invoke_command'
/var/lib/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/var/lib/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/vendor/thor/lib/thor/base.rb:440:in`start'
/var/lib/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/cli.rb:11:in `start'
/var/lib/gems/2.1.0/gems/bundler-1.12.0.rc/exe/bundle:27:in`block in <top (required)>'
/var/lib/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/var/lib/gems/2.1.0/gems/bundler-1.12.0.rc/exe/bundle:19:in`<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in`<main>'
E, [2016-09-05T15:31:22.934748 #1723] ERROR -- : Aborted with HUP signal

**Comment by olemskoi** [comment]
Попробуйте использовать последнюю версию. Мы исправили много ошибок в этом направлении.
