### ISSUE TITLE
Не устанавливается

### ISSUE THREAD

**Issue by ecnr33** [centosadmin/redmine_intouch#102]
При bundle install - ошибка

```
[!] There was an error parsing `Gemfile`: 
[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice with different version requirements.
You specified: minitest-reporters (<= 1.3.0) and minitest-reporters (>= 0). Bundler cannot continue.

 #  from /var/www/redmine/plugins/redmine_intouch/Gemfile:8
 #  -------------------------------------------
 #  group :test do
 >    gem 'minitest-reporters'
 #    gem 'mocha'
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /var/www/redmine/Gemfile:120
 #  -------------------------------------------
 #  Dir.glob File.expand_path("../plugins/*/{Gemfile,PluginGemfile}", __FILE__) do |file|
 >    eval_gemfile file
 #  end
 #  -------------------------------------------
```

**Comment by funk-yourself** [comment]
Можете убрать в Gemfile плагина фиксированную версию у minitest-reporters: она была зафиксирована из-за бага в последней версии гема, но это нужно только для прохождения тестов.

**Comment by ecnr33** [comment]
в gemfile плагина такое содержимое
```gem 'pidfile', git: 'https://github.com/arturtr/pidfile.git'
gem 'sidekiq-failures', git: 'https://github.com/mhfs/sidekiq-failures.git', branch: 'master'
gem 'sidekiq-cron'
gem 'sidekiq-rate-limiter', git: 'https://github.com/centosadmin/sidekiq-rate-limiter', branch: 'master',
    require: 'sidekiq-rate-limiter/server'

group :test do
  gem 'minitest-reporters'
  gem 'mocha'
  gem 'shoulda'
end
```
ставлю из ветки master

**Comment by ecnr33** [comment]
в общем я понял - конфликтует gemfile из redmine_bots и gemfile из redmine_intouch
когда я выполняю команду RAILS_ENV=production bundle install - он почему то на оба эти файлы смотрит.
в gemfile redmine_bots версии прописаны, а в gemfile redmine_intouch версий нет, вот он и выдает ошибку

**Comment by funk-yourself** [comment]
Смержил ветку с прописанной версией в intouch только что, можно запуллить новую версию. Но в принципе, этот гем в production-окружении можно вообще удалить из гемфайлов.

**Comment by ecnr33** [comment]
Я вручную версии прописал чтобы не ругалось, плагин установился.
Сделал миграции, тоже успешно. После перезагрузки redmine перестал запускаться.
Может не запускаться redmine изза проблемы с sidekiq.yml?

Дело в том, что когда я его подкидываю согласно инструкции из папки extra в конфиг sidekiq, у меня перестает выполняться команда `bundle exec rake redmine:plugins:migrate RAILS_ENV=production`

Выдает такое ругательство:
```
rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/var/www/redmine/plugins/redmine_sidekiq/lib/redmine_sidekiq/configure.rb:13:in `<class:Configure>'
/var/www/redmine/plugins/redmine_sidekiq/lib/redmine_sidekiq/configure.rb:9:in `<module:RedmineSidekiq>'
/var/www/redmine/plugins/redmine_sidekiq/lib/redmine_sidekiq/configure.rb:8:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/var/www/redmine/plugins/redmine_sidekiq/init.rb:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/var/www/redmine/lib/redmine/plugin.rb:155:in `block in load'
```

**Comment by funk-yourself** [comment]
Конфиг где лежит? Должен в быть в plugins/redmine_sidekiq/config/sidekiq.yml

**Comment by ecnr33** [comment]
Да, конфиг не туда положил. В общем вроде ошибок нет теперь, но бот не реагирует на сообщения.

**Comment by ecnr33** [comment]
хочу уточнить 2 момента:
1) proxy sock5 использовать можно или только http?
2) https обязательно должен быть включен в настройках redmine или можно все-таки на http?

**Comment by funk-yourself** [comment]
> proxy sock5 использовать можно или только http?
Прокси для tdlib - socks5, для бота - http.

> https обязательно должен быть включен в настройках redmine или можно все-таки на http?
https нужен при использовании вебхуков. При запуске через getUpdates необязательно.

**Comment by ecnr33** [comment]
все получилось
