### ISSUE TITLE
Не добавляет супергруппу в список

### ISSUE THREAD

**Issue by itvdonsk** [centosadmin/redmine_intouch#13]
> E, [2016-10-08T17:13:50.419971 #1497] ERROR -- : UPDATE ERROR RangeError: 1001092186476 is out of range for ActiveRecord::Type::Integer with limit 4
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activerecord-4.2.5.2/lib/active_record/type/integer.rb:45:in `ensure_in_range'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activerecord-4.2.5.2/lib/active_record/type/integer.rb:23:in`type_cast_for_database'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/quoting.rb:13:in `quote'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract_adapter.rb:116:in`block in compile'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract_adapter.rb:116:in `map'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract_adapter.rb:116:in`compile'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/database_statements.rb:13:in `to_sql'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in`select_all'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activerecord-4.2.5.2/lib/active_record/querying.rb:39:in`find_by_sql'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activerecord-4.2.5.2/lib/active_record/relation.rb:639:in `exec_queries'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activerecord-4.2.5.2/lib/active_record/relation.rb:515:in`load'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activerecord-4.2.5.2/lib/active_record/relation.rb:243:in `to_a'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activerecord-4.2.5.2/lib/active_record/relation/finder_methods.rb:500:in`find_nth_with_limit'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activerecord-4.2.5.2/lib/active_record/relation/finder_methods.rb:484:in `find_nth'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activerecord-4.2.5.2/lib/active_record/relation/finder_methods.rb:127:in`first'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/protected_attributes-1.1.3/lib/active_record/mass_assignment_security/relation.rb:49:in `first_or_initialize'
> /var/data/redmine/plugins/redmine_intouch/lib/tasks/intouch.rake:91:in`block (4 levels) in <top (required)>'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/telegrammer-0.8.0/lib/telegrammer/bot.rb:71:in `block (2 levels) in get_updates'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/telegrammer-0.8.0/lib/telegrammer/bot.rb:68:in`each'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/telegrammer-0.8.0/lib/telegrammer/bot.rb:68:in `block in get_updates'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/telegrammer-0.8.0/lib/telegrammer/bot.rb:61:in`loop'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/telegrammer-0.8.0/lib/telegrammer/bot.rb:61:in `get_updates'
> /var/data/redmine/plugins/redmine_intouch/lib/tasks/intouch.rake:58:in`block (3 levels) in <top (required)>'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.5.0/lib/rake/task.rb:240:in`block in execute'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.5.0/lib/rake/task.rb:235:in`execute'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
> /usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/monitor.rb:211:in`mon_synchronize'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.5.0/lib/rake/task.rb:165:in`invoke'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.5.0/lib/rake/application.rb:106:in`block (2 levels) in top_level'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.5.0/lib/rake/application.rb:106:in`block in top_level'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.5.0/lib/rake/application.rb:100:in`top_level'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.5.0/lib/rake/application.rb:176:in`standard_exception_handling'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
> /usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.5.0/bin/rake:33:in`<top (required)>'
> /usr/local/rvm/gems/ruby-2.0.0-p643/bin/rake:23:in `load'
> /usr/local/rvm/gems/ruby-2.0.0-p643/bin/rake:23:in`<main>'
> /usr/local/rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `eval'
> /usr/local/rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in`<main>'

**Comment by olemskoi** [comment]
Если повторяется, пожалуйста, откройте задачу заново.
