### ISSUE TITLE
Не отправляет исполнителю

### ISSUE THREAD

**Issue by teddybear** [centosadmin/redmine_intouch#2]
Привет! Обнаружил странное поведение, при одинаково выставленных настройках для всех трех вкладок (Автор, Исполнитель, Наблюдатели), сообщение в Телеграм отправляется только если юзер назначен Автором или Наблюдаетелем. То есть, если человек помечен только как исполнитель — сообщение не приходит. 
Начал копаться, обнаружил, что если здесь https://github.com/centosadmin/redmine_intouch/blob/master/lib/intouch/patches/issue_patch.rb#L86
Убрать условие, то все начинает работать, поскольку `project.assigner_ids.include?(assigned_to_id)` всегда возвращает nil.
Кроме того, эта ветка условия https://github.com/centosadmin/redmine_intouch/blob/master/lib/intouch/patches/issue_patch.rb#L83, тоже настораживает =)

**Comment by arturtr** [comment]
Нужно в настройках плагина для проекта указать группы исполнителей. Это сделано для того, чтоб уведомления получали только работники компании.

**Comment by teddybear** [comment]
Ок, понял, спасибо! =)
