### ISSUE TITLE
Не могу изменить расписание переодических задач

### ISSUE THREAD

**Issue by 4ev** [centosadmin/redmine_intouch#23]
После нажатия кнопки сохранить, получаю сообщение 

Forbidden

![image](https://cloud.githubusercontent.com/assets/20472402/21001612/43f388ca-bd43-11e6-8f3c-ad66eead9373.png)

![image](https://cloud.githubusercontent.com/assets/20472402/21001623/54a1e978-bd43-11e6-9ebe-4b9072500a80.png)

В логе пишет:

Started PUT "/sidekiq_cron_jobs/cron_unassigned_regular_notification" for 10.1.8.220 at 2016-12-08 12:35:04 +0500

Может расписание можно где нибудь в файле конфига прописать?

**Comment by arturtr** [comment]
А https://github.com/ogom/redmine_sidekiq у вас установлен?

После `Started PUT "/sidekiq_cron_jobs/cron_unassigned_regular_notification"` в логе есть надписи?

**Comment by 4ev** [comment]
redmine_sidekiq установлен. После Started PUT "/sidekiq_cron_jobs/cron_unassigned_regular_notification" в логе записей нет.

**Comment by arturtr** [comment]
а в sidekiq.log есть что-то?

у себя мы не смогли повторить эту ошибку

**Comment by 4ev** [comment]
только это:

D, [2016-12-13T14:39:08.333393 #25283] DEBUG -- : Sidekiq client with redis options {:url=>nil}
I, [2016-12-13T14:39:08.344193 #25283]  INFO -- : Cron Jobs - add job with name: Telegram Group Auto Close - every 1 hour
I, [2016-12-13T14:39:08.346438 #25283]  INFO -- : Cron Jobs - add job with name: Telegram Group Daily Report - every day
D, [2016-12-13T14:39:08.390664 #25284] DEBUG -- : Sidekiq client with redis options {:url=>nil}
I, [2016-12-13T14:39:08.399316 #25284]  INFO -- : Cron Jobs - add job with name: Telegram Group Auto Close - every 1 hour
I, [2016-12-13T14:39:08.406235 #25284]  INFO -- : Cron Jobs - add job with name: Telegram Group Daily Report - every day

**Comment by arturtr** [comment]
А какая у вас версия  redmine?

Приложите заодно содержимое `Gemfile.lock`

и список усталовленных плагинов
`ls plugins`

**Comment by arturtr** [comment]
А также скрин со списком плагинов из redmine чтоб можно было номера версий плагинов видеть

**Comment by 4ev** [comment]
redmine 3.3.0 

root@Redmine:/opt/redmine-3.3.0# ls plugins
accept                     redmine_issue_history
clipboard_image_paste      redmine_issues_tree
periodictask               redmine_issue_templates
README                     redmine_last_updated_by_column
redmine_agile              redmine_lightbox2
redmine_chat_telegram      redmine_local_avatars
redmine_checklists         redmine_login_audit
redmine_close_button       redmine_monitoring_controlling
redmine_contacts           redmine_shady
redmine_email_fetcher      redmine_sidekiq
redmine_extended_watchers  redmine_stats
redmine_impersonate        redmine_telegram_common
redmine_intouch            redmine_tweaks
redmine_issue_badge        redmine_xlsx_format_issue_exporter
redmine_issue_completion   sidebar_hide
redmine_issue_favicon      telegrammer

[Gemfile.zip](https://github.com/centosadmin/redmine_intouch/files/648532/Gemfile.zip)

**Comment by arturtr** [comment]
Попробуйте обновить 
`bundle update sidekiq sidekiq-cron rufus-scheduler`

и плагины `redmine_telegram_common` и `redmine_intouch` через `git pull`

**Comment by 4ev** [comment]
Все сделал, не помогает.

Installing sidekiq 4.2.7 (was 4.1.4)
Installing sidekiq-cron 0.4.5 (was 0.4.2)
Installing rufus-scheduler 3.3.1 (was 3.2.1)

Redmine Intouch plugin 0.3.5

Redmine Telegram Common plugin 0.0.11

**Comment by arturtr** [comment]
Возможно в логах unicorn (puma, passenger) что-то есть?
Или в nginx (apache)?

Очень странная ситуация
