### ISSUE TITLE
Bot crashes every time if you forgot to specify an address on /connect command

### ISSUE THREAD

**Issue by sergiotejon** [centosadmin/redmine_intouch#24]
Hi,

Once you run the bot the first time, it works properly using every command like /start and /help. But if you use /connect command without any address on it to link your telegram account with your redmine, the Bot crashes every time you run it.

I tried to find out a way to rerun the bot, but the only one I found was to create a new one and set the new token up again on the configuration page. Then the bot runs properly.

If you don't forget to specify an email address on /connect command the bot works properly and doesn't crash.

Thanks.

**Comment by sergiotejon** [comment]
The last git version both of them.. 
I've tried to run this on a docker container version of Redmine (https://hub.docker.com/_/redmine/).

**Comment by ipcross** [comment]
Strangely.
Now, command '/connect' without email send message `Wrong email. User with this email not found.` Need logs.

**Comment by ipcross** [comment]
Need bot log and rails log, can you send it?

**Comment by sergiotejon** [comment]
The most strange it doesn't show any logs when this happens. I was watching it when I redid the problem. 
I'm thinking could be the ruby versión on this container I was using. I've just realised on it and I checked which version it is. 

ruby 2.2.6p396 (2016-11-15 revision 56800) [x86_64-linux]

This plugin needs 2.3+, so that must be the fail. 

Sorry.

**Comment by ipcross** [comment]
Yes, try to update ruby version.

**Comment by sergiotejon** [comment]
Sorry for opening again this issue,

I realize I was working with a little modified version of redmine_telegram_common plugin. It was working with this ruby version with this bug. 

Due to upgrade ruby is difficult for me, I fix this behaviour. Attached you can find a patch that solve this problem using ruby 2.2.6, if you consider allow this ruby version with this plugin.

[redmine_telegram_common-ruby_v2.2.6.patch.txt](https://github.com/centosadmin/redmine_intouch/files/710055/redmine_telegram_common-ruby_v2.2.6.patch.txt)

Thanks a lot for your time and sorry for the inconvenience.

**Comment by arturtr** [comment]
Hello @sergiotejon!

What difficult in ruby upgrade? RVM on rbenv can help you to install any version of ruby.

You can find instructions here (for example):
https://gorails.com/setup/ubuntu/16.04

or here: https://rvm.io/

**Comment by arturtr** [comment]
docker example for ruby 2.3

https://github.com/docker-library/ruby/blob/c1d5f251adad058eec8bc3b6476ab204f2e6dba1/2.3/Dockerfile

**Comment by sergiotejon** [comment]
Thanks @arturtr,

Really, that's not difficult to upgrade, but I'm interested in keeping my running docker container version of redmine (it's the official docker container) and this one works over ruby 2.2.6. Only that.

As soon as I need to modify that docker image to something more personalized I will upgrade that ruby version to the latest one. In the meantime It's much easier for me adapt this code. 

I take note about your recommendations,
Thanks again.
