### ISSUE TITLE
redmine_sidekiq how to?

### ISSUE THREAD

**Issue by ijakparov** [centosadmin/redmine_intouch#27]
Hello, I'm trying to setup second of your plugins but I dont understand how to setup redmine_sidekiq.
Shoud I use only your config in example? Too many dependencies I've sped all my day for setup and still no result. Help me with your advice.

**Comment by ipcross** [comment]
Hi. try:
1. Install Redis. https://redis.io/topics/quickstart 
2. Start Redis: 
$ redis-server 
3. Install redmine_sidekiq:
$ git clone https://github.com/ogom/redmine_sidekiq ./plugins/redmine_sidekiq
$ bundle install
4. Copy sidekiq.yml:
$ cp ./plugins/redmine_intouch/extras/sidekiq.yml ./config/sidekiq.yml
5. Start sidekiq:
$ sidekiq

**Comment by ipcross** [comment]
Describe your problem more.
I'll try to help.
