### ISSUE TITLE
ActionView::Template::Error

### ISSUE THREAD

**Issue by evgarik** [centosadmin/redmine_intouch#28]
Здравствуйте, воткнулся вот в такую проблему
 
Rendered projects/settings.html.erb within layouts/base (289.0ms)
Completed 500 Internal Server Error in 310ms (ActiveRecord: 28.0ms)

ActionView::Template::Error (undefined method `render_intouch_tabs' for #<#<Class:0x0000080c294320>:0x00000813af81e0>):
    10:       }
    11:     end %>
    12:
    13:     <%= render_intouch_tabs settings_source, issue_update_tabs %>
    14:
    15:   </div>
    16:
  plugins/redmine_intouch/app/views/projects/settings/intouch/common/_settings.html.erb:13:in `_plugins_redmine_intouch_app_views_projects_settings_intouch_common__settings_html_erb___37282162228286723_17277706860'
  plugins/redmine_intouch/app/views/projects/settings/intouch/_settings.html.erb:29:in `block in _plugins_redmine_intouch_app_views_projects_settings_intouch__settings_html_erb___273180490908919840_17278191640'
  plugins/redmine_intouch/app/views/projects/settings/intouch/_settings.html.erb:8:in `_plugins_redmine_intouch_app_views_projects_settings_intouch__settings_html_erb___273180490908919840_17278191640'

Environment:
  Redmine version                3.3.2.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [amd64-freebsd10]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2            
Redmine plugins:
  redmine_intouch                0.4.0
  redmine_sidekiq                2.1.0
  redmine_telegram_common        0.0.14

Пожалуйста, помогите победить?

**Comment by olemskoi** [comment]
Здравствуйте.
Вы запускали plugins migrations?

**Comment by evgarik** [comment]
Конечно, инструкцию установки полностью выполнил

**Comment by evgarik** [comment]
Проблема появляется когда я активирую плагин на проекте.
В настройках у самого модуля все нормально работает.

**Comment by olemskoi** [comment]
Какая версия ruby используется?

**Comment by evgarik** [comment]
Environment:
Redmine version 3.3.2.stable
Ruby version 2.3.3-p222 (2016-11-21) [amd64-freebsd10]
Rails version 4.2.7.1
Environment production
Database adapter Mysql2
Redmine plugins:
redmine_intouch 0.4.0
redmine_sidekiq 2.1.0
redmine_telegram_common 0.0.14

**Comment by evgarik** [comment]
поставил более новый 
redmine_telegram_common        0.0.15

**Comment by evgarik** [comment]
Результат тотже  :(

**Comment by evgarik** [comment]
Нашел временный выход.
Сконфигурировал в настройках плагина шаблон.
потом удалил злополучную строчку
<%= render_intouch_tabs settings_source, issue_update_tabs %>

Вошел в проект и установил ему работу по шаблону.
Вроде все работает.
Но редактировать или создать новый шаблон в таком виде уже не получится.
Поэтому придется возвращать строчку каждый раз, как захочу изменить шаблон.
Вот такой костыль кривой.
Посмотрите пожалуйста почему же может не работать в нормальном виде.

**Comment by evgarik** [comment]
Не сильно спасает, видимо все же надо делать настройки и в проекте, а то индивидуальные сообщения приходят только автору при создании задачи

**Comment by olemskoi** [comment]
Проверим и исправим в течение нескольких дней.

**Comment by ipcross** [comment]
Пытаюсь воспроизвести ошибку.

**Comment by ipcross** [comment]
evgarik, опишите подробнее последовательность действий, которая приводит к ошибки. У меня пока не получается ее повторить.

**Comment by evgarik** [comment]
Установил все что необходимо для плагина.
Потом установил сам плагин.
Делаю первичные настройки на странице настройки плагина.
Захожу в настройки проекта.
Подключаю плагин к проекту и и после нажатия на кнопку сохранить, получаю вылет с 500 ошибкой.
Дамп лога на момент ошибки смотрите выше.

**Comment by arturtr** [comment]
@evgarik добрый день!

Попробуйте обновиться из ветки https://github.com/centosadmin/redmine_intouch/tree/render_intouch_tabs_fix

и напишите об итогах

**Comment by ipcross** [comment]
evgarik, получилось решить проблему с помощью этого патча?

**Comment by evgarik** [comment]
Rendered projects/settings.html.erb within layouts/base (53.4ms)
Completed 500 Internal Server Error in 70ms (ActiveRecord: 3.9ms)

ActionView::Template::Error (super: no superclass method `project_settings_tabs' for #<#<Class:0x000008160db150>:0x000008162b2ac8>):
    1: <h2><%=l(:label_settings)%></h2>
    2:
    3: <%= render_tabs project_settings_tabs %>
    4:
    5: <% html_title(l(:label_settings)) -%>
  plugins/redmine_intouch/lib/intouch/patches/projects_helper_patch.rb:8:in `project_settings_tabs'
  plugins/redmine_finance/lib/redmine_finance/patches/projects_helper_patch.rb:38:in `project_settings_tabs_with_finance'
  app/views/projects/settings.html.erb:3:in `_app_views_projects_settings_html_erb___2213089126761750582_17343601340'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by ipcross** [comment]
На версии редмайна 3.3.2 удалось повторить ошибку. Исправляю.

**Comment by evgarik** [comment]
Спасибо, очень жду :)

**Comment by ipcross** [comment]
Оу, попробуй redmine_intouch из мастера (не из ветки), а redmine_telegram_common обнови до 0.0.15 - у меня работает.

**Comment by evgarik** [comment]
Processing by ProjectsController#settings as HTML
  Parameters: {"id"=>"shoppinggo"}
  Current user: Evgarik (id=5)
  Rendered projects/_form.html.erb (32.1ms)
  Rendered projects/_edit.html.erb (33.6ms)
  Rendered projects/settings/_modules.html.erb (11.2ms)
  Rendered projects/settings/_members.html.erb (46.4ms)
  Rendered plugins/scrum/app/views/projects/settings/_sprints.html.erb (23.8ms)
  Rendered projects/settings/_versions.html.erb (11.5ms)
  Rendered projects/settings/_issue_categories.html.erb (9.5ms)
  Rendered projects/settings/_wiki.html.erb (1.7ms)
  Rendered projects/settings/_repositories.html.erb (5.2ms)
  Rendered projects/settings/_activities.html.erb (9.4ms)
  Rendered plugins/redmine_contacts/app/views/projects/_contacts_settings.html.erb (0.9ms)
  Rendered plugins/redmine_intouch/app/views/projects/settings/intouch/common/_settings.html.erb (197.4ms)
  Rendered plugins/redmine_intouch/app/views/projects/settings/intouch/_settings.html.erb (203.4ms)
  Rendered common/_tabs.html.erb (368.6ms)
  Rendered projects/settings.html.erb within layouts/base (369.8ms)
Completed 500 Internal Server Error in 396ms (ActiveRecord: 26.7ms)

ActionView::Template::Error (undefined method `render_intouch_tabs' for #<#<Class:0x00000815631da8>:0x00000810eada40>):
    10:       }
    11:     end %>
    12:
    13:     <%= render_intouch_tabs settings_source, issue_update_tabs %>
    14:
    15:   </div>
    16:
  plugins/redmine_intouch/app/views/projects/settings/intouch/common/_settings.html.erb:13:in `_plugins_redmine_intouch_app_views_projects_settings_intouch_common__settings_html_erb___2038785820792198554_17362665060'
  plugins/redmine_intouch/app/views/projects/settings/intouch/_settings.html.erb:29:in `block in _plugins_redmine_intouch_app_views_projects_settings_intouch__settings_html_erb__4416107734852471135_17366921860'
  plugins/redmine_intouch/app/views/projects/settings/intouch/_settings.html.erb:8:in `_plugins_redmine_intouch_app_views_projects_settings_intouch__settings_html_erb__4416107734852471135_17366921860'
  app/views/common/_tabs.html.erb:17:in `block in _app_views_common__tabs_html_erb__1700105805221212334_17281306180'
  app/views/common/_tabs.html.erb:16:in `each'
  app/views/common/_tabs.html.erb:16:in `_app_views_common__tabs_html_erb__1700105805221212334_17281306180'
  app/helpers/application_helper.rb:325:in `render_tabs'
  app/views/projects/settings.html.erb:3:in `_app_views_projects_settings_html_erb___3915343507054817422_17281388120'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'






Вот Инфо о системе и плагины котоыре стоят
Environment:
  Redmine version                3.3.2.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [amd64-freebsd10]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  mega_calendar                  1.4.0
  redmine_agile                  1.4.2
  redmine_checklists             3.1.5
  redmine_contacts               4.0.5
  redmine_contacts_invoices      4.1.3
  redmine_finance                2.1.1
  redmine_intouch                0.4.0
  redmine_sidekiq                2.1.0
  redmine_telegram_common        0.0.15
  scrum                          0.16.2

**Comment by arturtr** [comment]
Добрый день @evgarik 
Удалось воспроизвести подобную ошибку, код исправляющий её находится в ветке
https://github.com/centosadmin/redmine_intouch/tree/project-helper-fix

Проверьте как у вас он заработает :)

**Comment by evgarik** [comment]
rocessing by ProjectsController#settings as HTML
  Parameters: {"id"=>"shoppinggo"}
  Current user: Evgarik (id=5)
  Rendered projects/_form.html.erb (19.8ms)
  Rendered projects/_edit.html.erb (20.9ms)
  Rendered projects/settings/_modules.html.erb (5.4ms)
  Rendered projects/settings/_members.html.erb (26.4ms)
  Rendered plugins/scrum/app/views/projects/settings/_sprints.html.erb (52.0ms)
  Rendered projects/settings/_versions.html.erb (19.7ms)
  Rendered projects/settings/_issue_categories.html.erb (9.4ms)
  Rendered projects/settings/_wiki.html.erb (1.5ms)
  Rendered projects/settings/_repositories.html.erb (5.1ms)
  Rendered projects/settings/_activities.html.erb (9.3ms)
  Rendered plugins/redmine_contacts/app/views/projects/_contacts_settings.html.erb (1.0ms)
  Rendered plugins/redmine_intouch/app/views/projects/settings/intouch/common/_settings.html.erb (127.4ms)
  Rendered plugins/redmine_intouch/app/views/projects/settings/intouch/_settings.html.erb (132.5ms)
  Rendered common/_tabs.html.erb (289.9ms)
  Rendered projects/settings.html.erb within layouts/base (290.5ms)
Completed 500 Internal Server Error in 308ms (ActiveRecord: 62.2ms)

ActionView::Template::Error (undefined method `render_intouch_tabs' for #<#<Class:0x0000080c6a9820>:0x000008154c55a0>):
    10:       }
    11:     end %>
    12:
    13:     <%= render_intouch_tabs settings_source, issue_update_tabs %>
    14:
    15:   </div>
    16:
  plugins/redmine_intouch/app/views/projects/settings/intouch/common/_settings.html.erb:13:in `_plugins_redmine_intouch_app_views_projects_settings_intouch_common__settings_html_erb__2433141071006856177_17376005200'
  plugins/redmine_intouch/app/views/projects/settings/intouch/_settings.html.erb:29:in `block in _plugins_redmine_intouch_app_views_projects_settings_intouch__settings_html_erb___2775105646420139691_17376698600'
  plugins/redmine_intouch/app/views/projects/settings/intouch/_settings.html.erb:8:in `_plugins_redmine_intouch_app_views_projects_settings_intouch__settings_html_erb___2775105646420139691_17376698600'
  app/views/common/_tabs.html.erb:17:in `block in _app_views_common__tabs_html_erb___4521000350432769661_17345217880'
  app/views/common/_tabs.html.erb:16:in `each'
  app/views/common/_tabs.html.erb:16:in `_app_views_common__tabs_html_erb___4521000350432769661_17345217880'
  app/helpers/application_helper.rb:325:in `render_tabs'
  app/views/projects/settings.html.erb:3:in `_app_views_projects_settings_html_erb___4333300657272221092_17284202200'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by arturtr** [comment]
Всё то же самое. Вы плагин из ветки project-helper-fix установили?

**Comment by evgarik** [comment]
1.Удалил старый плагин.
2.Перезапустил редмайн.
3.Поставил плагин   
`git clone -b project-helper-fix https://github.com/centosadmin/redmine_intouch.git plugins/redmine_intouch`
4.Перезапустил редмайн
5.Снял логи tail -f log/production.log

**Comment by arturtr** [comment]
Попробуйте ещё раз из той же ветки обновиться.

**Comment by evgarik** [comment]
без изменений

**Comment by arturtr** [comment]
@evgarik Новый релиз в той же ветке.

Теперь точно должно заработать :) Проверьте пожалуйста.

Если всё ок - оформим релиз.

**Comment by evgarik** [comment]
Работает!
Интересный вариант решения :)
