### ISSUE TITLE
Не приходят уведомления в telegram.

### ISSUE THREAD

**Issue by peektoseen** [centosadmin/redmine_intouch#29]
Почему то в логе log/intouch/telegram-live-sender.log следующее:

```D, [2017-02-04T01:53:36.686721 #59226] DEBUG -- : START for issue_id 85
D, [2017-02-04T01:53:36.689470 #59226] DEBUG -- : #<Issue id: 85, tracker_id: 2, project_id: 1, subject: "Telegram бот для redmine", description: "Установить и настроить бота для оповещений об изме...", due_date: nil, category_id: nil, status_id: 2, assigned_to_id: 1, priority_id: 1, fixed_version_id: nil, author_id: 5, lock_version: 12, created_on: "2016-11-08 11:48:11", updated_on: "2017-02-03 22:53:28", start_date: "2016-11-08", done_ratio: 0, estimated_hours: nil, parent_id: nil, root_id: 85, lft: 1, rgt: 2, is_private: false, closed_on: nil, intouch_data: {"last_notification"=>{"working"=>2017-02-04 01:50:25 +0300}}>
D, [2017-02-04T01:53:37.421739 #59226] DEBUG -- : base_message: `NETGO WIFI: Telegram бот для redmine`
Обновил: Николай YYYYYYYY
Статус: Тестирование -> Выполняется
Назначена: Николай YYYYYYYY
*Приоритет: !!! Низкий !!!*
http://redmine.*********.com/issues/85
D, [2017-02-04T01:53:38.648935 #59226] DEBUG -- : user: #<User id: 5, login: "*********@#####.ru", hashed_password: "ee583bfed013e93e860ea93b9f73ce0ac0f03751", firstname: "Иван", lastname: "ААААААА", admin: false, status: 3, last_login_on: "2017-01-23 11:40:34", language: "ru", auth_source_id: nil, created_on: "2016-10-04 11:02:58", updated_on: "2017-02-02 11:12:14", type: "User", identity_url: nil, mail_notification: "selected", salt: "7d29db037b0e9df8b46b10bd44312b7e", must_change_passwd: false, passwd_changed_on: "2016-11-10 10:20:34">
D, [2017-02-04T01:53:38.650062 #59226] DEBUG -- : telegram_account: nil
D, [2017-02-04T01:53:38.650147 #59226] DEBUG -- : FINISH for issue_id 85
```

Насколько я понял из строчки ```DEBUG -- : telegram_account: nil``` - нет аккаунтов, которым будет отправлено это сообщение. Но у меня абсолютно везде в настройках плагина включены все галочки для всех пользователей/групп/статусов. Что я упустил? 

Скрины настроек:
http://joxi.ru/82QE8QDCxoq42d
http://joxi.ru/5md5RY0SzWZK21
http://joxi.ru/52aEKz8Czodx20

**Comment by evgarik** [comment]
такое делали?
Чтобы связать аккаунты Redmine и Telegram, пожалуйста, введите команду "/connect login@redmine.com",
где login@redmine.com - ваш E-Mail в Redmine.

**Comment by peektoseen** [comment]
Да, делал, вот ответ сейчас от бота:
"Ваши аккаунты уже связаны".
До этого связывал аккаунт с почтой и на почту приходило подтверждение с ссылкой.

**Comment by ipcross** [comment]
Добрый день, peektoseen.
Если судить по вашему логу, то пользователь с id=5 не имеет привязанный телеграм аккаунт.

Давайте это проверим и выполним в рельсовой консоли:
>>  User.find(5).telegram_account

Какой вернется результат?

**Comment by peektoseen** [comment]
ID моего пользователя - 1 (это admin), вот вывод для этого пользователя:
```
irb(main):014:0* User.find(1).telegram_account
=> #<TelegramCommon::Account id: 1, telegram_id: 92473368, username: "peektoseen", first_name: "Николай", last_name: "Чучадеев", user_id: 1, active: true, token: "xai7Reimebeil7lonoh2moo7aiDo2air7", blocked: false, connect_trials_count: 1>
```

**Comment by ipcross** [comment]
Правильно, вот для этого пользователя придет уведомление. Но в логе выше, этому пользователю сообщение не посылается. Назначте задачу на админа и покажите лог, как выше.

**Comment by ipcross** [comment]
peektosee, получилось ли разобраться с плагином?

**Comment by peektoseen** [comment]
Извиняюсь за поздний ответ. Да, разобраться удалось. Я не так понял логику работы уведомлений. Считал что если пользователь с id=1 каким-либо образом участвовал в задаче (например в ходе задачи он был исполнителем в какое-то время или писал коммент) - то он получит уведомление если в эту задачу добавили комментарий.

**Comment by ipcross** [comment]
Отлично. Удачи.
