### ISSUE TITLE
Бот пытается создать массу своих копий и их же убить

### ISSUE THREAD

**Issue by teddybear** [centosadmin/redmine_intouch#3]
При апдейте до 23 версии получил факап с rake-таском, который добавляет юзеров. Почему-то, после внедрения проверки на pid, он бесконечно себя создает и убивает, пришлось вырезать все начиная с https://github.com/centosadmin/redmine_intouch/blob/master/lib/tasks/intouch.rake#L110

**Comment by arturtr** [comment]
В последнем релизе убрали управление ботопроцессами. Теперь таких коллизий быть не должно
