### ISSUE TITLE
Как управлять пользователями подключенными к телеграмм (связанными аккаунтами)?

### ISSUE THREAD

**Issue by mirkhamidov** [centosadmin/redmine_intouch#32]
Надо было подключить еще одного пользователя, он набрал у себя в телеграмме `/connect ...`, ему выдало:
![photo_2017-02-17_11-42-25](https://cloud.githubusercontent.com/assets/2736223/23058488/4256397c-f506-11e6-8126-6c343268485a.jpg)

В редмайне это мыло есть, проверил, набрал сам, со своего аккаунта, теперь мне не приходят уведомления, а ему уходят все что мне предназначено.
Посмотрел вывод в консоли `TelegramCommon::Account.all` (не уверен в правильности `all`)
```
irb(main):023:0* TelegramCommon::Account.all
=> #<ActiveRecord::Relation [#<TelegramCommon::Account id: 1, telegram_id: 8**4, username: "miroff", first_name: "Jasur", last_name: "Mirkhamidov", user_id: 5, active: true, token: "9***9", connect_trials_count: 0, blocked_at: nil>, #<TelegramCommon::Account id: 3, telegram_id: 2**9, username: "miroff", first_name: "Jasur", last_name: "Mirkhamidov", user_id: nil, active: true, token: "a***6", connect_trials_count: 0, blocked_at: nil>]>
```

PS: Поняв ситуацию, я опять у себя перенабрал `/connect ...` уже со своим мылом, вывод выше, после этого действия

**Comment by mirkhamidov** [comment]
Переустановил все, вроде теперь работает нормально, в прошлый раз второй аккаунт забыл выполнить `/start`

**Comment by mirkhamidov** [comment]
Ой, и все же, как управлять связанными пользователями? Если скажем, из команды ушел человек!

**Comment by ipcross** [comment]
Я рад, что у вас все получилось. По порядку, команда /start как раз создает запись в  TelegramCommon::Account c telegram_id пользователя, который хочет подключиться. Без этой команды будет команда выше. Если из команды ушел человек, то вы просто его аккаунт блокируете в редмайне и все. Он не будет получать сообщения.
