### ISSUE TITLE
Не могу настроить отправку писем

### ISSUE THREAD

**Issue by mv-maltsev** [centosadmin/redmine_intouch#39]
Здравствуйте!

Установил плагин по инструкции. Сделал настройки уведомлений. Добавил настройки для проекта, но письма не приходят. Телеграмм не настраивал пока, интересует уведомления на почту. Письма от самого редмайна всегда приходили и приходят, а от плагина нет. Не могу понять, куда копать. Подскажите, пожалуйста.
**Инфа о Redmine:**
http://joxi.ru/bmozPREuxoW8dr
**Общие настройки плагина:**
http://joxi.ru/DrloYKgCvnEX8A
**Периодические задачи**
http://joxi.ru/823x7WduJKO76A

**Настройки в проекте:**

http://joxi.ru/zANYRMztBxgGy2

http://joxi.ru/Q2KYKgzt4XRenr

**Comment by arturtr** [comment]
Возможно дело в формате интервала. Заметил у вас там `0,1`, хотя лучше бы через точку писать `0.1`

**Comment by arturtr** [comment]
Хотя live-уведомления должны без этого приходить.

Запущен ли у вас сайдкик?
Насколько его конфиг соответствует этому?
https://github.com/centosadmin/redmine_intouch/blob/master/extras/sidekiq.yml

**Comment by mv-maltsev** [comment]
`# Sample configuration file for Sidekiq.
# Place this file at config/sidekiq.yml and Sidekiq will
# pick it up automatically.
---
:pidfile: tmp/pids/sidekiq.pid
:logfile: log/sidekiq.log
:timeout: 30
:queues:
  - default`

Попробовал написать 0.1, но после сохранения все равно возвращается запятая.

**Comment by mv-maltsev** [comment]
Вот что открывается по ссылке на сайдкик из редмайна
http://joxi.ru/KAxoPpBCMqQx52

**Comment by arturtr** [comment]
В очередях должна быть очередь telegram в конфиге

пт, 17 марта 2017, 23:18 mv-maltsev <notifications@github.com>:

**Comment by arturtr** [comment]
Гляньте пример конфигурации, что я выше привел

сб, 18 марта 2017, 11:50 Артур Трофимов <arturtr@gmail.com>:

**Comment by mv-maltsev** [comment]
Заменил конфиг тот, который вы привели по ссылке. Скажите, а для того, чтобы новый конфиг применился, нужно что-то сделать?

**Comment by mv-maltsev** [comment]
Обязательно ли настраивать телеграм-бота для того, чтобы получать письма на почту?

**Comment by arturtr** [comment]
> Заменил конфиг тот, который вы привели по ссылке. Скажите, а для того, чтобы новый конфиг применился, нужно что-то сделать?

Нужно sidekiq перезапустить

> Обязательно ли настраивать телеграм-бота для того, чтобы получать письма на почту?
Нет.

Скиньте, к стати, скрин страницы "Очереди"

**Comment by mv-maltsev** [comment]
> Скиньте, к стати, скрин страницы "Очереди"

Скрин http://joxi.ru/Q2KYKgzt4X7JMr

Подскажите, пожалуйста, а как сайдик перезапустить?

**Comment by mv-maltsev** [comment]
Очередь телеграм так и не появилась в очереди. Надо сайдик перезапустить, только не знаю как.

**Comment by olemskoi** [comment]
У вас CentOS? Устанавливали init.d-скрипт? Как?

Без вводных данных самое простое и некрасивое решение - рестарт всей машины. После рестарта проверьте "ps aux | grep sidekiq" - чтобы sidekiq был запущен.

**Comment by mv-maltsev** [comment]
Init.d скрипт не устанавливал.
У меня виртуальный хостинг на Beget.ru. У них Ubuntu c docker. В docker установлен redmine. Поэтому я не могу сделать рестарт всей машины.

**Comment by olemskoi** [comment]
Попробуйте рестартовать sidekiq с помощью sidekiqctl restart.

**Comment by mv-maltsev** [comment]
Вызвал
```
(docker) mozgius@everest2:~/mozgius.bget.ru [0] $ sidekiqctl restart
sidekiqctl - stop a Sidekiq process from the command line.
Usage: sidekiqctl <command> <pidfile> <kill_timeout>
 where <command> is either 'quiet' or 'stop'
       <pidfile> is path to a pidfile
       <kill_timeout> is number of seconds to wait until Sidekiq exits
       (default: 10), after which Sidekiq will be KILL'd
Be sure to set the kill_timeout LONGER than Sidekiq's -t timeout.  If you want
to wait 60 seconds for jobs to finish, use `sidekiq -t 60` and `sidekiqctl stop
 path_to_pidfile 61`
```

Попробовал установить init.d-скрипт из папки extras
```
(docker) mozgius@everest2:~/mozgius.bget.ru/plugins/redmine_intouch/extras [0] $ sh redmine-sidekiq 
redmine-sidekiq: 9: .: Can't open /etc/init.d/functions
```

**Comment by olemskoi** [comment]
Как вы запускали sidekiq изначально? Попробуйте запустить "sidekiqctl stop", а потом запустить заново. Если не получится, вам стоит обратиться к системным администраторам.

**Comment by mv-maltsev** [comment]
> Как вы запускали sidekiq изначально? Попробуйте запустить "sidekiqctl stop", а потом запустить заново. Если не получится, вам стоит обратиться к системным администраторам.
Я его не запускал как то специально, я установил плагин redmine_sidekiq. Скажите, а на данный момент проблема только в sidekiq?

То же самое:
```
(docker) mozgius@everest2:~/mozgius.bget.ru/plugins/redmine_intouch/extras [2] $ sideki
qctl stop
sidekiqctl - stop a Sidekiq process from the command line.
Usage: sidekiqctl <command> <pidfile> <kill_timeout>
 where <command> is either 'quiet' or 'stop'
       <pidfile> is path to a pidfile
       <kill_timeout> is number of seconds to wait until Sidekiq exits
       (default: 10), after which Sidekiq will be KILL'd
Be sure to set the kill_timeout LONGER than Sidekiq's -t timeout.  If you want
to wait 60 seconds for jobs to finish, use `sidekiq -t 60` and `sidekiqctl stop
 path_to_pidfile 61`
```

**Comment by olemskoi** [comment]
> Я его не запускал как то специально, я установил плагин redmine_sidekiq. Скажите, а на данный момент проблема только в sidekiq?

С большой вероятностью. Вам нужно перезапустить sidekiq, найдите системных администраторов, которые это сделают.

После перезапуска проверьте, что появилась нужная очередь в админке sidekiq.

Если проблема не решится, откройте задачу заново.

**Comment by mv-maltsev** [comment]
Хорошо, спасибо. Отпишусь.
