### ISSUE TITLE
Failed in Redmine 3.3.1.stable version

### ISSUE THREAD

**Issue by candy-liu** [centosadmin/redmine_intouch#42]
Notice an internal Error after deploy

**Comment by olemskoi** [comment]
Did you run migrations? Did you install redmine_telegram_common plugin?

Please paste error messages from production.log via xpaste.pro.

**Comment by candy-liu** [comment]
@olemskoi 
hmmm,  we only use outlook send emails,  didn't install redmine_telegram_common
 Started GET "/settings/plugin/redmine_intouch" for 10.120.100.89 at 2017-03-28 13:24:05 +0800
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_intouch"}
  Current user: root (id=1)
Scoped order and limit are ignored, it's forced to be batch order and batch size
  Rendered plugins/redmine_intouch/app/views/settings/_common.html.erb (10.0ms)
  Rendered plugins/redmine_intouch/app/views/settings/_telegram.html.erb (7.7ms)
  Rendered common/_tabs.html.erb (20.8ms)
  Rendered plugins/redmine_intouch/app/views/settings/_intouch.html.erb (21.9ms)
  Rendered settings/plugin.html.erb within layouts/admin (23.7ms)
Completed 500 Internal Server Error in 42ms (ActiveRecord: 11.3ms)

ActionView::Template::Error (Mysql2::Error: Table 'redmine.telegram_group_chats' doesn't exist: SELECT `telegram_group_chats`.* FROM `telegram_group_chats`):
     7: 
     8: <table class="list">
     9:   <tbody>
    10:   <% for telegram_group in TelegramGroupChat.all %>
    11:     <tr class="<%= cycle("odd", "even") %>">
    12:       <td class="name">
    13:         <%= telegram_group.title %>
  plugins/redmine_intouch/app/views/settings/_telegram.html.erb:10:in `_54b0483899ecd36d00088839b584a050'
  app/views/common/_tabs.html.erb:17:in `block in _6e596986c8ef70d375d661d10d442bce'
  app/views/common/_tabs.html.erb:16:in `each'
  app/views/common/_tabs.html.erb:16:in `_6e596986c8ef70d375d661d10d442bce'
  app/helpers/application_helper.rb:325:in `render_tabs'
  plugins/redmine_intouch/app/views/settings/_intouch.html.erb:22:in `_c3e70e003e6550ec1027929caf23d7eb'
  app/views/settings/plugin.html.erb:6:in `block in _ff1df436d83b2832666fcab0272b299a'
  app/views/settings/plugin.html.erb:4:in `_ff1df436d83b2832666fcab0272b299a'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by olemskoi** [comment]
Please read README file and install all requirements.
