### ISSUE TITLE
Перестала работать отправка уведомлений при изменениях в задачах

### ISSUE THREAD

**Issue by heap2015** [centosadmin/redmine_intouch#43]
`2017-03-29T14:15:20.974Z 639 TID-6nqg4 WARN: NameError: undefined local variable or method `telegram_group' for #<Issue:0x00000004b35250>`

Заккоментировал тут:
/plugins/redmine_intouch/lib/intouch/patches/issue_patch.rb
```
228             #if telegram_group.present? && telegram_group.shared_url.present?                                                                                                                                                            
229             #  message += ", [#{I18n.t('intouch.telegram_message.issue.telegram_link')}](#{telegram_group.shared_url})"                                                                                                                  
230             #end
```                                                     
и все заработало

**Comment by arturtr** [comment]
Спасибо, что заметили. Дело в том, что telegram_group добавляется в другом нашем плагине 
https://github.com/centosadmin/redmine_chat_telegram

Не учли, что кто-то только intouch может использовать.

**Comment by arturtr** [comment]
В свежем релизе баг исправлен. Спасибо за участие в улучшении плагина 👍
