### ISSUE TITLE
Ошибка в redmine 3.3

### ISSUE THREAD

**Issue by ololoshashepard** [centosadmin/redmine_intouch#48]
установка проходит нормально, но при входе на страницу задачи 500 ошибка
в логах:
ActiveRecord::DangerousAttributeError (delay is defined by Active Record. Check to make sure that you don't have an attribute or method with the same name.):
  app/models/issue_relation.rb:109:in `initialize'
  app/controllers/issues_controller.rb:112:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by juxta73** [comment]
такая же история

**Comment by olemskoi** [comment]
Какие у вас установлены плагины?
Возможно ли увидеть больший кусок лога?

**Comment by constXife** [comment]
@ololoshashepard, попробуйте поставить новую версию плагина(1.0.0), возможно она решит Ваши проблемы.
