### ISSUE TITLE
ActionView::Template::Error

### ISSUE THREAD

**Issue by gledsoncruz** [centosadmin/redmine_intouch#5]
By accessing the url:
http://10.1.0.115:3000/projects/gisportal/settings/
I got the following error:
This error occurs after I activate intouch plugin in my project:

Started GET "/projects/gisportal/settings/" for 10.1.3.114 at 2016-08-25 09:23:53 -0300
Processing by ProjectsController#settings as HTML
  Parameters: {"id"=>"gisportal"}
  Current user: gledson.cruz (id=5)
  Rendered projects/_form.html.erb (18.6ms)
  Rendered projects/_edit.html.erb (20.3ms)
  Rendered projects/settings/_modules.html.erb (5.6ms)
  Rendered projects/settings/_members.html.erb (14.3ms)
  Rendered plugins/advanced_roadmap_v2/app/views/projects/settings/_milestones.html.erb (2.1ms)
  Rendered projects/settings/_versions.html.erb (4.5ms)
  Rendered projects/settings/_issue_categories.html.erb (2.2ms)
  Rendered projects/settings/_wiki.html.erb (1.9ms)
  Rendered plugins/redmine_git_hosting/app/views/projects/settings/_repositories.html.haml (14.4ms)
  Rendered projects/settings/_boards.html.erb (2.2ms)
  Rendered projects/settings/_activities.html.erb (10.7ms)
  Rendered plugins/redmine_intouch/app/views/projects/settings/intouch/common/_settings.html.erb (179.8ms)
  Rendered plugins/redmine_intouch/app/views/projects/settings/intouch/_settings.html.erb (185.3ms)
  Rendered common/_tabs.html.erb (273.4ms)
  Rendered projects/settings.html.erb within layouts/base (274.2ms)
Completed 500 Internal Server Error in 293ms (ActiveRecord: 17.9ms)

ActionView::Template::Error (undefined method `render_intouch_tabs' for #<#<Class:0x007fa7a63797b8>:0x007fa7a0a0ef48>):
    10:       }
    11:     end %>
    12: 
    13:     <%= render_intouch_tabs settings_source, issue_update_tabs %>
    14: 
    15:   </div>
    16: 
  plugins/redmine_intouch/app/views/projects/settings/intouch/common/_settings.html.erb:13:in`_plugins_redmine_intouch_app_views_projects_settings_intouch_common__settings_html_erb__2329897050763101602_43279640'
  plugins/redmine_intouch/app/views/projects/settings/intouch/_settings.html.erb:29:in `block in _plugins_redmine_intouch_app_views_projects_settings_intouch__settings_html_erb__3182936809133082087_44108340'
  plugins/redmine_intouch/app/views/projects/settings/intouch/_settings.html.erb:8:in`_plugins_redmine_intouch_app_views_projects_settings_intouch__settings_html_erb__3182936809133082087_44108340'
  app/views/common/_tabs.html.erb:17:in `block in _app_views_common__tabs_html_erb___3675473855529715786_70178827571580'
  app/views/common/_tabs.html.erb:16:in`each'
  app/views/common/_tabs.html.erb:16:in `_app_views_common__tabs_html_erb___3675473855529715786_70178827571580'
  app/helpers/application_helper.rb:325:in`render_tabs'
  app/views/projects/settings.html.erb:3:in `_app_views_projects_settings_html_erb___3270537101440791841_70179011938440'
  lib/redmine/sudo_mode.rb:63:in`sudo_mode'

Can you help me?

**Comment by arturtr** [comment]
Which version of redmine do you use?

**Comment by gledsoncruz** [comment]
3.2

Em 25 de ago de 2016 19:21, "Artur Trofimov" <notifications@github.com>
escreveu:

**Comment by gledsoncruz** [comment]
I tested with version 3.3 and occurred the same problem....

**Comment by olemskoi** [comment]
Please check that you use ruby >2.3. And the latest version of plugin.
If error still occures, please open the task again.
