### ISSUE TITLE
Где указывать групповые чаты?

### ISSUE THREAD

**Issue by ATerechshenkov** [centosadmin/redmine_intouch#51]
Подскажите, как добавляются групповые чаты? 

![image](https://user-images.githubusercontent.com/1052539/27321604-a0a69e6a-55bc-11e7-8dfb-9a751833bcb3.png)

О Redmine:
Environment:
  Redmine version                3.3.3.stable
  Ruby version                   2.3.0-p0 (2015-12-25) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.4.3
  redmine_checklists             3.1.5
  redmine_default_assign         0.6
  redmine_image_clipboard_paste  1.0.0
  redmine_intouch                0.6.2
  redmine_local_avatars          1.0.0
  redmine_sidekiq                2.1.0
  redmine_telegram_common        0.0.15
  sidebar_hide                   0.0.8

**Comment by olemskoi** [comment]
Вы пробовали добавлять бота в группу?

**Comment by ATerechshenkov** [comment]
Да. Он в группе

**Comment by olemskoi** [comment]
А rake-задачи запущены?

**Comment by ATerechshenkov** [comment]
Вы имеете ввиду миграции? Они выполннились.
Какие процессы, как это проверить?

**Comment by olemskoi** [comment]
ps ax | grep rake

У вас установлен telegram-cli?

**Comment by ATerechshenkov** [comment]
Не запущены,
Не установлен.

В описании установки про это ничего не написано

**Comment by olemskoi** [comment]
Мы сейчас готовим новую версию, будут существенные изменения. Если не к спеху, дождитесь конца недели. Заодно и документацию проверим.

**Comment by ATerechshenkov** [comment]
Спасибо. Подожду. Пока работает другой модуль, но там настройки ограничены, на любой чих сообщения кидает.

**Comment by arturtr** [comment]
@ATerechshenkov а чем сейчас пользуетесь? Любопытно посмотреть на конкурирующие плагины

**Comment by arturtr** [comment]
telegram-cli тут не нужен
Должен быть запущен бото-процесс

https://github.com/centosadmin/redmine_intouch#bot-launch

**Comment by ATerechshenkov** [comment]
Вот этот плагин: https://github.com/ANemcov/redmine_telegram

Спасибо. Получилось подключить бота, он мне отправил преветственное приглашение.
Hello, people! I've added this group chat for Redmine notifications.

Теперь не получается настроить уведомления.

Я зашел в нужный мне проект, в котором мы хотим получать уведомления в групповой чат только при создании новой задачи в статусе Open. Включил модуль в проекте и указал галочки как на принтскрине, все остальное не трогал.
![image](https://user-images.githubusercontent.com/1052539/27328950-b306c314-55d5-11e7-81f2-0661a83a2a66.png)

При создании или изменении статуса в Open или Приоритета, ничего не приходит.
Что еще может быть не так?

**Comment by constXife** [comment]
@ATerechshenkov, добрый день, попробуйте поставить новую версию нашего плагина — 1.0.0. Возможно там Ваша проблема решена. И если нет, то мы постараемся решить её.
