### ISSUE TITLE
Перестали приходить уведомления после перезагрузки сервера.

### ISSUE THREAD

**Issue by peektoseen** [centosadmin/redmine_intouch#54]
Где-то что-то нужно запустить видимо, не могу понять где, уведомления раньше работали стабильно, до перезагрузки сервера.

**Comment by olemskoi** [comment]
Попробуйте установить новые версии плагинов.

**Comment by peektoseen** [comment]
Обновился, не приходят.

**Comment by olemskoi** [comment]
Отправьте скан страницы с версиями плагинов.

Так же проверьте, что настроили redmine telegram common.

**Comment by peektoseen** [comment]
Скрин: http://joxi.ru/J2bYZV9u4V0XEm

**Comment by peektoseen** [comment]
Смотрю логи, пока наткнулся на один WARNING:
W, [2017-07-18T14:55:04.166127 #52179]  WARN -- : NameError: uninitialized constant TelegramMessageSender::Telegram
W, [2017-07-18T14:55:04.166193 #52179]  WARN -- : /usr/share/redmine/plugins/redmine_intouch/app/workers/telegram_message_sender.rb:15:in `perform'

**Comment by peektoseen** [comment]
bot = Telegram::Bot::Client.new(token)
Вот тут не может найти что такое "Telegram", откуда должен браться этот класс и где он подключается?

**Comment by constXife** [comment]
Telegram::Bot::Client — это класс из гема telegram-bot-ruby. Подключаться должен автоматически вместе с другими гемами.

**Comment by olemskoi** [comment]
Вы делали bundle exec gem install?

**Comment by peektoseen** [comment]
Видимо нет, при попытке сделать  bundle exec gem install получаю:
ERROR:  While executing gem ... (Gem::CommandLineError)
    Please specify at least one gem name (e.g. gem build GEMNAME)

**Comment by olemskoi** [comment]
Вероятнее всего, в этом и проблема. Вам нужно установить зависимости гемов.

**Comment by constXife** [comment]
Надо запускать команду bundle install.

**Comment by peektoseen** [comment]
Не помогает, делаю bundle install:

$ bundle install
Your Gemfile lists the gem pidfile (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of one of them later.
Your Gemfile lists the gem sidekiq-cron (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of one of them later.
Your Gemfile lists the gem sidekiq-rate-limiter (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of one of them later.
Your Gemfile lists the gem telegram-bot-ruby (<= 0.7.2) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of one of them later.
Your Gemfile lists the gem minitest-reporters (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of one of them later.
Your Gemfile lists the gem shoulda (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of one of them later.
Using rake 11.3.0
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.9.1
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Using nokogiri 1.6.7.2
Using rack 1.6.4
Using mime-types 2.6.1
Using arel 6.0.3
Using addressable 2.4.0
Using ansi 1.5.0
Using ice_nine 0.11.2
Using bundler 1.15.2
Using byebug 9.0.6
Using docile 1.1.5
Using simplecov-html 0.10.0
Using coderay 1.1.1
Using concurrent-ruby 1.0.2
Using connection_pool 2.2.1
Using database_cleaner 1.5.1
Using equalizer 0.0.11
Using multipart-post 2.0.0
Using htmlentities 4.3.3
Using thor 0.19.1
Using metaclass 0.0.4
Using ruby-progressbar 1.8.1
Using mysql2 0.4.4
Using net-ldap 0.12.1
Using pidfile 0.3.1 from https://github.com/arturtr/pidfile.git (at master@e19bdb3)
Using ruby-openid 2.7.0
Using rbpdf-font 1.19.0
Using redcarpet 3.3.4
Using redis 3.3.2
Using request_store 1.3.0
Using rmagick 2.15.4
Using shoulda-context 1.2.2
Using tilt 2.0.5
Using spy 0.4.5
Using timecop 0.9.1
Using minitest-around 0.4.0
Using tzinfo 1.2.2
Using descendants_tracker 0.0.4
Using loofah 2.0.3
Using rack-test 0.6.3
Using rack-protection 1.5.3
Using mail 2.6.3
Using css_parser 1.3.7
Using simplecov 0.12.0
Using sprockets 3.7.0
Using faraday 0.12.1
Using mocha 1.2.1
Using minitest-reporters 1.1.14
Using rack-openid 1.4.2
Using rbpdf 1.19.0
Using redis-namespace 1.5.2
Using redis_rate_limiter 0.1.0
Using activesupport 4.2.6
Using rufus-scheduler 3.3.1
Using axiom-types 0.1.1
Using coercible 1.0.0
Using rails-html-sanitizer 1.0.3
Using sidekiq 4.2.7
Using sinatra 1.4.7
Using roadie 3.1.1
Using codeclimate-test-reporter 0.6.0
Using rails-deprecated_sanitizer 1.0.3
Using globalid 0.3.6
Using activemodel 4.2.6
Using shoulda-matchers 2.8.0
Using virtus 1.0.5
Using sidekiq-cron 0.4.5
Using sidekiq-failures 1.0.0 from https://github.com/mhfs/sidekiq-failures.git (at master@bcc15b6)
Using sidekiq-rate-limiter 0.1.1 from https://github.com/centosadmin/sidekiq-rate-limiter (at master@d95520a)
Using rails-dom-testing 1.0.6
Using activejob 4.2.6
Using activerecord 4.2.6
Using protected_attributes 1.1.3
Using shoulda 3.5.0
Using telegram-bot-ruby 0.7.2
Using actionview 4.2.6
Using actionpack 4.2.6
Using actionmailer 4.2.6
Using actionpack-action_caching 1.1.1
Using actionpack-xml_parser 1.0.2
Using railties 4.2.6
Using sprockets-rails 2.3.2
Using jquery-rails 4.0.5
Using roadie-rails 1.1.0
Using rails 4.2.6
Bundle complete! 47 Gemfile dependencies, 91 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.


В логах по-прежнему:
W, [2017-07-25T16:48:30.876603 #59605]  WARN -- : NameError: uninitialized constant TelegramMessageSender::Telegram
W, [2017-07-25T16:48:30.876680 #59605]  WARN -- : /usr/share/redmine/plugins/redmine_intouch/app/workers/telegram_message_sender.rb:15:in `perform'

**Comment by arturtr** [comment]
А редмайн перезапустили при этом?

С уважением,
Артур Трофимов


2017-07-25 23:50 GMT+10:00 peektoseen <notifications@github.com>:

**Comment by peektoseen** [comment]
Да, даже ребутался.

**Comment by iamkapman** [comment]
Похожая проблема. При попытке инициализировать WebHook бота в логах:

> NameError (uninitialized constant IntouchController::Telegram):
>   plugins/redmine_intouch/app/controllers/intouch_controller.rb:19:in `bot_init'
>   lib/redmine/sudo_mode.rb:63:in `sudo_mode'

В 19 строке файла intouch_controller.rb также
`bot = Telegram::Bot::Client.new(Intouch.bot_token)`

Установлены:

> Environment:
>   Redmine version                3.3.2.stable
>   Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux]
>   Rails version                  4.2.7.1
>   Environment                    production
>   Database adapter               Mysql2
> SCM:
>   Subversion                     1.8.10
>   Git                            2.1.4
>   Filesystem                     
> Redmine plugins:
>   a_common_libs                  2.2.8
>   ajax_counters                  1.4.0
>   redmine_agile                  1.4.2
>   redmine_chat_telegram          2.0.0
>   redmine_checklists             3.1.5
>   redmine_extended_watchers      1.0.5
>   redmine_intouch                1.0.0
>   redmine_issue_tabs             1.1.1
>   redmine_lightbox2              0.3.2
>   redmine_local_avatars          1.0.3
>   redmine_sidekiq                2.1.0
>   redmine_telegram_common        0.1.2
>   unread_issues                  2.1.0

**Comment by peektoseen** [comment]
up

**Comment by constXife** [comment]
Попробуйте обновить плагин с ветки develop и снова запустить.

**Comment by iamkapman** [comment]
Мне помогло. Спасибо!
