### ISSUE TITLE
Не приходят уведомления в telegram, не отрабатываются /log, /task, etc

### ISSUE THREAD

**Issue by nicksonet** [centosadmin/redmine_intouch#58]
Добрый день.
У меня установлены:
Redmine version                          3.3.4.stable
Ruby version                                2.3.4-p301 (2017-03-30) [x86_64-linux-gnu]
redmine_sidekiq                           2.1.0
redmine_telegram_common        0.1.2
redmine_intouch                          1.0.1

rm работает чз https

Бот активировался, 
чат в теле задачи создается,
но:
- Не приходит нотификация об изменениях в задаче,
- при использовании /log, /task, etc - ничего не происходит, но в /sidekiq/queues/telegram?poll=true
при каждом выполнении  /log, /task.. в очереди sidekiq появляется новая операция. 

Коллеги, подскажите, пожалуйста, что я мог сделать не так

**Comment by constXife** [comment]
Добрый день, покажите скриншот страницы /sidekiq/busy?

**Comment by walkmanyd** [comment]
[2017-10-22T17:02:36.603817 #6278] DEBUG -- : https://redmine.xxxx.xxx/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%7D&command=Test
Push messaging is not supported.
success: api test
Error creating/accessing IndexedDB database [object Event]
   https://redmine.xxxx.xxx/plugin_assets/redmine_telegram_common/webogram/js/app.js : 23
'waitFor()' finished in 1016ms.

**Comment by makarich** [comment]
Так же бот активировался, но никаких уведомлений не приходит.
на команды /start /connect бот не отвечает
созданные группы не видит

**Comment by funk-yourself** [comment]
We recommend to upgrade to the [latest master version](https://github.com/centosadmin/redmine_telegram_common) of redmine_telegram_common.

**Comment by olemskoi** [comment]
Здравствуйте. Если последние версии наших плагинов из master не помогут, пожалуйста, переоткройте или поставьте новую задачу.
