### ISSUE TITLE
ответ телеграм бота не уходит к пользователю

### ISSUE THREAD

**Issue by alexanderbr** [centosadmin/redmine_intouch#60]
При попытке отправить команду боту, он ее читает, судя по логу отправляет ответ, но он не доходит.

intouch/bot.log:
```
D, [2017-12-18T13:39:53.161167 #253] DEBUG -- : TelegramCommon::Bot#send_message
D, [2017-12-18T13:39:53.162015 #253] DEBUG -- : chat_id: xxx
D, [2017-12-18T13:39:53.162696 #253] DEBUG -- : message: /start - Начало работы с ботом
/connect - связать аккаунты Telegram и Redmine
/update - обновить информацию об аккаунте Telegram (если сменили имя или ник)
/help - справка по командам
D, [2017-12-18T13:39:53.164869 #253] DEBUG -- : params: {}
```
в веб интерфейсе sidekiq:
`Telegram::Bot::Exceptions::ResponseError: Telegram API has returned the error. (ok: "false", error_code: "404", description: "Not Found")`

**Comment by olemskoi** [comment]
Здравствуйте. Пожалуйста, проверьте, что для каждого из плагинов используется отдельный бот.
