### ISSUE TITLE
Бот не отравляет ответы клиенту

### ISSUE THREAD

**Issue by hatsnal** [centosadmin/redmine_intouch#65]
Информация о сервере: 

ОС: Centos 7

Environment:
  Redmine version                3.4.4.stable
  Ruby version                   2.5.0-p0 (2017-12-25) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            1.8.3.1
  Filesystem                     
Redmine plugins:
  redmine_intouch                1.0.1
  redmine_sidekiq                2.1.0
  redmine_telegram_common        0.1.3

Бот не отправляет ответы, но в логах мелькают запросы от телеграмма: 

Started POST "/intouch/web_hook" for 149.154.167.227 at 2018-02-02 18:04:00 +0500

Весит очеред sideqik

**Comment by olemskoi** [comment]
Вы используете только этот плагин или redmine_chat_telegram, redmine_2fa тоже? Обратите внимание, что для каждого из плагинов нужно создавать отдельного бота.

**Comment by hatsnal** [comment]
@olemskoi почему тикет закрыли? Использую только intouch

**Comment by olemskoi** [comment]
Вы инициализировали webhooks?
Sidekiq запущен?

**Comment by hatsnal** [comment]
@olemskoi да, приложил ведь лог, в логе видно что идут запросы к боту

**Comment by olemskoi** [comment]
Я могу посмотреть настройки, но мне понадобится доступ админом к редмайну. Напишите мне на почту, если такой вариант приемлем.

igor@southbridge.io

**Comment by olemskoi** [comment]
Попробуйте последние версии. Если не поможет - откройте заново задачу.
