### ISSUE TITLE
#65

### ISSUE THREAD

**Issue by hatsnal** [centosadmin/redmine_intouch#66]
Информация о сервере:

ОС: Centos 7

Environment:
Redmine version 3.4.4.stable
Ruby version 2.5.0-p0 (2017-12-25) [x86_64-linux]
Rails version 4.2.8
Environment production
Database adapter Mysql2
SCM:
Git 1.8.3.1
Filesystem
Redmine plugins:
redmine_intouch 1.0.1
redmine_sidekiq 2.1.0
redmine_telegram_common 0.1.3

Бот не отправляет ответы, но в логах мелькают запросы от телеграмма:

Started POST "/intouch/web_hook" for 149.154.167.227 at 2018-02-02 18:04:00 +0500

Весит очеред sideqik

**Comment by hatsnal** [comment]
@olemskoi из #65 пояснения: все тестировалось исключительно с intouch, chat telegram не устанавливал еще да же

**Comment by olemskoi** [comment]
Попробуйте последние версии. Если не поможет - откройте заново задачу.
