### ISSUE TITLE
Проблема при установке

### ISSUE THREAD

**Issue by Promethei** [centosadmin/redmine_intouch#68]
При выполнении команды "bundle install RAILS_ENV=production" ошибка
ERROR: "bundle install" was called with arguments ["RAILS_ENV=production"]
Usage: "bundle install [OPTIONS]"

может чего не хватает?

**Comment by olemskoi** [comment]
Укажите RAILS_ENV=production перед командой, а не внутри.

**Comment by Promethei** [comment]
Спасибо)
