### ISSUE TITLE
не отправляются сообщения по расписанию

### ISSUE THREAD

**Issue by esuslik** [centosadmin/redmine_intouch#70]
Redis сервер запущен
Sidekiq запущен
Плагин настроен на отправку уведомлений по email
В панели sidekiq показывает что события есть, но они не падают в задачи и уведомления не ходят.
Cron инициализирован.
![screenshot-2018-2-20 sidekiq](https://user-images.githubusercontent.com/16290583/36422718-22b43594-165f-11e8-9197-7fd9b419c4aa.png)
Где копать и какие логи смотреть?

Ubuntu server 16.04 lts
Environment:
  Redmine version                3.4.4.stable
  Ruby version                   2.3.1-p112 (2016-04-26) [x86_64-linux-gnu]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Filesystem                     
Redmine plugins:
  a_common_libs                  2.4.3
  custom_menu                    1.8.2
  redmine_anonymous_authors      0.0.4
  redmine_ckeditor               1.1.4
  redmine_contacts               4.1.1
  redmine_contacts_helpdesk      3.0.9
  redmine_intouch                1.0.2
  redmine_issue_favicon          0.0.3
  redmine_per_project_formatting 0.0.4
  redmine_sidekiq                2.1.0
  redmine_telegram_common        0.2.0
  sidebar_hide                   0.0.8
  unread_issues                  2.2.1

**Comment by esuslik** [comment]
Telegram уведомления победтл, ходят, но как-то хаотично, как буд-то настройки свои где-то стоят. Email ни в какую.
Есть подозрение что возможно глюк связан с тем что до этого момента стояла старая версия плагина и новая наложилась не корректно.
Есть ли способ полностью очистить все настройки и кэши плагина? Чтобы произвести чистую настройку

**Comment by olemskoi** [comment]
Покажите скриншоты настроек. У вас один проект или несколько используют уведомления? Через шаблоны настроены уведомления или индивидуально?
Пробовали смотреть sidekiq log, там все в порядке или ошибки сыпятся?
Последние версии плагинов используете (вчера был релиз новых версий)?

**Comment by esuslik** [comment]
плагины обновил.
Уведомления используются во всех проектах, примерно 30шт.
Заведено 2 шаблона. В настройках каждого проекта эти шаблоны выбраны.

Обратил внимание что в паели sidekiq при запске задания cron по просроченым задачам в задание падает только 2 задания, только 2 задачи, хотя фактически их больше. То есть в выборку по просроченым по какой-то причине не попадают задачи.

**Comment by olemskoi** [comment]
Надо смотреть настройки. Пока идей нет.

**Comment by esuslik** [comment]
могу скинуть скрины и выдержки из логов. Какую информацию дать?

**Comment by esuslik** [comment]
Может ли быть что таблицы и настройки в бд сохранились от совсем старых версий плагина?
Возможно ли как-то почистить эту инфу и настройить с нуля?

**Comment by olemskoi** [comment]
Покажите скрины настроек, пожалуйста.

**Comment by esuslik** [comment]
![screenshot-2018-2-21 redmine intouch plugin - - - intouch1](https://user-images.githubusercontent.com/16290583/36467124-28e025ea-16ff-11e8-942e-9dd8ecc11285.png)
![screenshot-2018-2-21 redmine intouch plugin - - - intouch2](https://user-images.githubusercontent.com/16290583/36467125-291101b0-16ff-11e8-9ca9-da44ff66547a.png)
![screenshot-2018-2-21 - redmine intouch plugin3](https://user-images.githubusercontent.com/16290583/36467126-29395e3a-16ff-11e8-9f2e-aa3851a787c9.png)
![screenshot-2018-2-21 - redmine intouch plugin4](https://user-images.githubusercontent.com/16290583/36467127-2961d90a-16ff-11e8-98cf-d784e8cf0878.png)
![screenshot-2018-2-21 - redmine intouch plugin5](https://user-images.githubusercontent.com/16290583/36467128-2984ff70-16ff-11e8-8888-4f3c5231e3bf.png)

**Comment by esuslik** [comment]
в телеграм уведомления приходят по факту, но как-то странно, в настройках стоит по крону проверять каждые 15 минут на просроченые задачи, а сообщения приходят с интервалом 2 часа и 2 часа 15 минут

**Comment by olemskoi** [comment]
Может попробовать заново инициализировать крон?

**Comment by esuslik** [comment]
как это сделать? В панели sidekiq во вкладке cron показывает задания, и отрабатывает их как надо по нужному расписанию. Возможно надо где-то еще посмотреть настройки крона?

**Comment by olemskoi** [comment]
Если во вкладке заданий все в порядке, значит с этим все ок. Я позже еще гляну скриншоты.

**Comment by esuslik** [comment]
Похоже разобрался в проблеме. Теперь на почту приходят уведомления. В телеграм тоже приходят. Еще понаблюдаю насчет перриодичности.
Проблема была из-за старта sidekiq 
Нашел на гитхабе демон под ubuntu сервер, немного подправил, запустил и все заработало. 
Если необходим инит скрипт для ubuntu сервер могу скинуть

**Comment by olemskoi** [comment]
Поздравляю!

Следите за обновлениями, в репозитории уже выложены коммиты для работы с API Telegram.

> Если необходим инит скрипт для ubuntu сервер могу скинуть

Мы всегда рады pull request-ам.

**Comment by esuslik** [comment]
как отправить вам скрипт? не знаю как pull реквестить

**Comment by olemskoi** [comment]
Нужно создать у себя форк и так далее. Скорее всего об этом есть инструкции.
