### ISSUE TITLE
Как обновиться до 1.1.0

### ISSUE THREAD

**Issue by Promethei** [centosadmin/redmine_intouch#75]
Как обновить модули intouch и common до последних? И версию ruby  2.3. надо обновлять?

**Comment by olemskoi** [comment]
Читайте README.

cd plugins/redmine_intouch; git pull
bundle install RAILS_ENV=production
bundle exec rake redmine:plugins:migrate RAILS_ENV=production

Аналогично остальные плагины.

Мы используем ruby 2.5.0. ruby 2.3 тоже должен работать.
