### ISSUE TITLE
Бот не отвечает на команды

### ISSUE THREAD

**Issue by Promethei** [centosadmin/redmine_intouch#76]
Бот не отвечает на команды start connect. Инициализация проходит успешно. И авторизация тоже. В логах чисто. Только в production.log записи такие
Started GET "/sidekiq/stats" for мой_ip at 2018-03-03 21:51:55 +0300
Started GET "/sidekiq/stats" for мой_ip at 2018-03-03 21:51:57 +0300
через каждые 2 секунды такие записи. 
sidekiq работает. В очереди пусто

**Comment by olemskoi** [comment]
Покажите список плагинов с версиями.
Какая версия Redmine? Какая версия ruby?

**Comment by Promethei** [comment]
![default](https://user-images.githubusercontent.com/36633109/36941536-af7bd64a-1f6e-11e8-80ea-07acca5a9f4b.png)

**Comment by olemskoi** [comment]
Процесс sidekiq запущен? Redis запущен?

Настройки плагина common выполнены?

**Comment by tesey27** [comment]
Да. Sidekiq работает, redis тоже. В настройках плагина прошёл инициализации и авторизовал по номеру телефона. Все вроде по инструкции

**Comment by olemskoi** [comment]
Как Вы настроили шаблон? Покажите скриншоты.

В проекте выбрали шаблон?

**Comment by olemskoi** [comment]
Можно еще попробовать для проверки установить плагин 2fa.

**Comment by Promethei** [comment]
![2018-03-05_18-18-25](https://user-images.githubusercontent.com/36633109/36979708-b70e38d8-20a1-11e8-965f-3419785165e6.png)

**Comment by Promethei** [comment]
У меня пока нет проектов. Только установил все. бот на команду старт даже не отвечает

**Comment by olemskoi** [comment]
Попробуйте установить еще redmine_2fa.

**Comment by Promethei** [comment]
Установил. Не отвечает. В логах также пусто

**Comment by olemskoi** [comment]
Попробуйте создать нового пользователя и войти под ним.

**Comment by Promethei** [comment]
В redmine или телеграмм?

**Comment by Promethei** [comment]
В редмайн создал юзера. При входе выбрал аутентификацию через телеграмм. По ссылке просил пройти на бота. Нажал старт, но тоже ничего не отвечает

**Comment by olemskoi** [comment]
Есть возможность предоставить доступ к «песочнице»?

**Comment by Promethei** [comment]
могу скинуть логин пароль на ящик

**Comment by Promethei** [comment]
какой email?

**Comment by olemskoi** [comment]
igor@southbridge.ru

**Comment by olemskoi** [comment]
Без прямого доступа к Redmine из интернет, плагин работать не будет. В этом и проблема.

**Comment by olemskoi** [comment]
Плюс важно, чтобы работало через https.
