### ISSUE TITLE
При установке плагина появилось сообщение о синтаксической ошибке 

### ISSUE THREAD

**Issue by zaur45** [centosadmin/redmine_intouch#8]
При установке плагина появилось сообщение о синтаксической ошибке:

```
 /opt/bitnami/apps/redmine/htdocs/plugins/redmine_intouch/lib/intouch/patches/issue_patch.rb:260: syntax error, unexpected <<
            message = <<~TEXT
                        ^ (SyntaxError)
```

Поскольку сам разработчиком не являюсь, воспользовался поиском. Совет отсюда помог, после замены "~" на "-" плагин установился и запустился: http://stackoverflow.com/questions/33319333/here-document-gives-eof-error-in-ruby-io

**Comment by YADeM** [comment]
Подписываюсь, та-же проблема. Заменил ~ на - и установилось.
Ubuntu 14.04.5 LTS

**Comment by arturtr** [comment]
Это синтаксис из ruby 2.3

Можно просто руби обновить
