### ISSUE TITLE
Сообщения изменились

### ISSUE THREAD

**Issue by komato3huk** [centosadmin/redmine_intouch#9]
!!! Напишите статус в задаче (бездействие # **0.7 ч**) !!! -   Время не корректно считает в часе не 70 минут. Было бы отлично если бы считались и минуты еденицами а не долями часа.
Заявки: Финальный тест заявки - тут раньше был трекер
Назначена: admin
Приоритет: 
Статус: В работе
http://test/issues/81
Все отлично. Но по возможности добавьте чтобы в тексте сообщения было описание или же конструктор для этих сообщений.

**Comment by olemskoi** [comment]
Время считается относительно. Доля от часа.

Шаблоны возможно добавим в будущем.
