### ISSUE TITLE
Ошибки закрытия телеграмм групп в sidekiq

### ISSUE THREAD

**Issue by esuslik** [centosadmin/redmine_intouch#92]
Следующая попытка | Кол-во попыток | Очередь | Задача | Аргументы | Ошибка

  | через 20 минут | 10 | default | TelegramGroupAutoCloseWorker |   | NameError: uninitialized constant TelegramGroupAutoCloseWorker
  | через 22 минуты | 12 | default | TelegramGroupAutoCloseWorker |   | NameError: uninitialized constant TelegramGroupAutoCloseWorker
  | через 31 минуту | 7 | default | TelegramGroupAutoCloseWorker |   | NameError: uninitialized constant TelegramGroupAutoCloseWorker
  | через 31 минуту | 9 | default | TelegramGroupAutoCloseWorker |   | NameError: uninitialized constant TelegramGroupAutoCloseWorker
  | через 33 минуты | 11 | default | TelegramGroupAutoCloseWorker |   | NameError: uninitialized constant TelegramGroupAutoCloseWorker
  | через 37 минут | 8 | default | TelegramGroupAutoCloseWorker |   | NameError: uninitialized constant TelegramGroupAutoCloseWorker
  | через час | 12 | default | TelegramGroupAutoCloseWorker |   | NameError: uninitialized constant TelegramGroupAutoCloseWorker
  | через час | 10 | default | TelegramGroupAutoCloseWorker |   | NameError: uninitialized constant TelegramGroupAutoCloseWorker
  | через час | 11 | default | TelegramGroupAutoCloseWorker |   | NameError: uninitialized constant TelegramGroupAutoCloseWorker
  | через час | 9 | default | TelegramGroupAutoCloseWorker |   | NameError: uninitialized constant TelegramGroupAutoCloseWorker
  | через 2 часа | 12 | default | TelegramGroupAutoCloseWorker |   | NameError: uninitialized constant TelegramGroupAutoCloseWorker
  | через 2 часа | 10 | default | TelegramGroupAutoCloseWorker |   | NameError: uninitialized constant TelegramGroupAutoCloseWorker
  | через 2 часа | 11 | default | TelegramGroupAutoCloseWorker |   | NameError: uninitialized constant TelegramGroupAutoCloseWorker
  | через 3 часа | 12 | default | TelegramGroupAutoCloseWorker |   | NameError: uninitialized constant TelegramGroupAutoCloseWorker
  | через 3 часа | 11 | default | TelegramGroupAutoCloseWorker |   | NameError: uninitialized constant TelegramGroupAutoCloseWorker
  | через 4 часа | 12 | default | TelegramGroupAutoCloseWorker |   | NameError: uninitialized constant TelegramGroupAutoCloseWorker
  | через 5 часов | 12 | default | TelegramGroupDailyReportCronWorker |   | NameError: uninitialized constant TelegramGroupDailyReportCronWorker
  | через 5 часов | 12 | default | TelegramGroupAutoCloseWorker |   | NameError: uninitialized constant TelegramGroupAutoCloseWorker
  | через 5 часов | 13 | default | TelegramGroupAutoCloseWorker |   |

**Comment by funk-yourself** [comment]
Это воркер плагина redmine_chat_telegram. Он установлен?
