### ISSUE TITLE
Не могу настроить расписание переодических задач

### ISSUE THREAD

**Issue by dronmaxman** [centosadmin/redmine_intouch#98]
OS Debian 9.1
ruby 2.3.3p222
Redmine version: 3.3.1
Database: mariadb

Где таблица?
![image](https://user-images.githubusercontent.com/15871669/42294178-b601f344-7fe7-11e8-9853-2c5a85441530.png)

Думаю, что таблица должна быть такой, но у меня она не отображается.
https://user-images.githubusercontent.com/16290583/36467125-291101b0-16ff-11e8-9ca9-da44ff66547a.png

**Comment by dronmaxman** [comment]
Нажимал.

![redmine-sheduler](https://user-images.githubusercontent.com/15871669/42294558-97b59bd6-7fea-11e8-9c49-1b963b769575.gif)

**Comment by olemskoi** [comment]
Что в логах при нажатии?

redmine_sidekiq установлен?

**Comment by dronmaxman** [comment]
Что в логах при нажатии?
Какой именно лог интересует?

redmine_sidekiq установлен?
да, установлен
![image](https://user-images.githubusercontent.com/15871669/42294686-987153de-7feb-11e8-8f88-357ad49bdeff.png)

**Comment by olemskoi** [comment]
production.log

**Comment by dronmaxman** [comment]
Лог открытия настроек redmine_intouch и нажатия "Инициализировать периодические задачи"
[production.log](https://github.com/centosadmin/redmine_intouch/files/2164408/production.log)

**Comment by funk-yourself** [comment]
По какой-то причине расписание не сохраняется в sidekiq-cron. Sidekiq правильно сконфигурирован?

К сожалению, сейчас в этом месте нет обработки ошибок, поэтому сложно сказать, что именно произошло.

Можно попробовать выполнить в консоли рельс следующий код и посмотреть результат:

```ruby
    hash = {
      'cron_feedback_regular_notification' => {
        'class' => 'CronFeedbackRegularNotification',
        'cron'  => '*/5 * * * *'
      },
      'cron_overdue_regular_notification' => {
        'class' => 'CronOverdueRegularNotification',
        'cron'  => '0 10 * * *'
      },
      'cron_unassigned_regular_notification' => {
        'class' => 'CronUnassignedRegularNotification',
        'cron'  => '*/15 * * * *'
      },
      'cron_working_regular_notification' => {
        'class' => 'CronWorkingRegularNotification',
        'cron'  => '*/5 * * * *'
      }
    }

    Sidekiq::Cron::Job.load_from_hash hash
```

**Comment by funk-yourself** [comment]
Если проблема не решена, переоткройте issue, пожалуйста.
